routes:
  /mobile-menu/:
    template: mobile-menu
    content_type: text/html
    data: false

collections:
  /:
    permalink: /{slug}/
    template: index19791984#2partA

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
